# **covert into dataframe**

In [1]:
import pandas as pd
import numpy as np

data = {
    "Customer_ID": [
        "C001", "C002", "C003", "C004", "C005",
        "C006", "C007", "C008", "C009", "C010",
        "C011", "C012", "C013", "C014", "C015",
        "C016", "C017", "C018", "C019", "C020",
        "C021", "C022", "C023", "C024", "C025",
        "C026", "C027", "C028", "C029", "C030"
    ],

    "Age": [
        23, 35, 29, 42, 26,
        31, 45, 28, 38, 24,
        33, 27, 41, 36, 22,
        30, 39, 25, 44, 32,
        28, 37, 46, 21, 34,
        40, 27, 43, 31, 36
    ],

    "Annual_Income": [
        28000, 62000, 45000, 85000, 32000,
        52000, 92000, 41000, 68000, 30000,
        58000, 38000, 78000, 65000, 24000,
        49000, 72000, 29000, 88000, 55000,
        43000, 70000, 95000, 22000, 60000,
        82000, 36000, 90000, 51000, 67000
    ],

    "Previous_Spending": [
        5000, 8000, 6500, 12000, 4500,
        7000, 14000, 6000, 10000, 4000,
        8500, 5500, 11000, 9000, 3500,
        6500, 10500, 4200, 13000, 7500,
        6000, 9500, 15000, 3000, 8000,
        12500, 5000, 13500, 7000, 10000
    ],

    "Target_Spending": [
        5600, 8800, 7200, 13500, 5100,
        7900, 15500, 6900, 11500, 4700,
        9300, 6200, 12500, 10100, 4100,
        7300, 11800, 5000, 14500, 8400,
        6900, 10500, 16500, 3600, 9000,
        13800, 5700, 15000, 7900, 11200
    ]
}

df = pd.DataFrame(data)

print(df)

   Customer_ID  Age  Annual_Income  Previous_Spending  Target_Spending
0         C001   23          28000               5000             5600
1         C002   35          62000               8000             8800
2         C003   29          45000               6500             7200
3         C004   42          85000              12000            13500
4         C005   26          32000               4500             5100
5         C006   31          52000               7000             7900
6         C007   45          92000              14000            15500
7         C008   28          41000               6000             6900
8         C009   38          68000              10000            11500
9         C010   24          30000               4000             4700
10        C011   33          58000               8500             9300
11        C012   27          38000               5500             6200
12        C013   41          78000              11000            12500
13        C014   36          65000               9000            10100
14        C015   22          24000               3500             4100
15        C016   30          49000               6500             7300
16        C017   39          72000              10500            11800
17        C018   25          29000               4200             5000
18        C019   44          88000              13000            14500
19        C020   32          55000               7500             8400
20        C021   28          43000               6000             6900
21        C022   37          70000               9500            10500
22        C023   46          95000              15000            16500
23        C024   21          22000               3000             3600
24        C025   34          60000               8000             9000
25        C026   40          82000              12500            13800
26        C027   27          36000               5000             5700
27        C028   43          90000              13500            15000
28        C029   31          51000               7000             7900
29        C030   36          67000              10000            11200

# **display first 5 rows**

In [ ]:
df.head()

  Customer_ID  Age  Annual_Income  Previous_Spending  Target_Spending
0        C001   23          28000               5000             5600
1        C002   35          62000               8000             8800
2        C003   29          45000               6500             7200
3        C004   42          85000              12000            13500
4        C005   26          32000               4500             5100

## **display last 5 rows**

In [3]:
df.tail()

   Customer_ID  Age  Annual_Income  Previous_Spending  Target_Spending
25        C026   40          82000              12500            13800
26        C027   27          36000               5000             5700
27        C028   43          90000              13500            15000
28        C029   31          51000               7000             7900
29        C030   36          67000              10000            11200